spring:
  datasource:
    name: dataSource
    url: jdbc:ArteryBase://localhost:5432/db_aty
    username: test
    password: ENCRYPT#QMi/uhoJ1tQ=
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.thunisoft.ArteryBase.Driver
